//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_Pharma_DB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_medicine
    {
        public long med_id { get; set; }
        public string med_name { get; set; }
        public string med_description { get; set; }
        public Nullable<int> med_qty { get; set; }
        public string med_expiry_date { get; set; }
        public string added_by { get; set; }
        public System.DateTime added_date { get; set; }
        public string updated_by { get; set; }
        public System.DateTime updated_date { get; set; }
        public bool is_active { get; set; }
        public long med_cat_id { get; set; }
        public string image_path { get; set; }
    
        public virtual tbl_med_category tbl_med_category { get; set; }
    }
}
