//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_Pharma_DB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_med_category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_med_category()
        {
            this.tbl_medicine = new HashSet<tbl_medicine>();
        }
    
        public long med_cat_id { get; set; }
        public string med_cat_name { get; set; }
        public string med_cat_description { get; set; }
        public string added_by { get; set; }
        public System.DateTime added_date { get; set; }
        public string updated_by { get; set; }
        public System.DateTime updated_date { get; set; }
        public bool is_active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_medicine> tbl_medicine { get; set; }
    }
}
